INSERT INTO documents (
    file_path, document_type, title, content_preview,
    line_count, created_at, indexed_at, source
) VALUES (
    'analysis_reports/README.md',
    'general_documentation',
    '📊 Analysis Reports',
    '# 📊 Analysis Reports

**Folder for generated analysis outputs**

---

## 📁 Contents

This folder contains all analysis reports generated by the autonomous system.

### **Current Reports:**

```
✅ ANAL',
    66,
    NOW(), NOW(), 'realtime_watcher'
)
ON CONFLICT (file_path) DO UPDATE SET
    document_type = EXCLUDED.document_type,
    title = EXCLUDED.title,
    indexed_at = NOW();